# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runners_Hi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8.2'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'lottie-ios'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'CHIPageControl', '~> 0.1.3'
  # Pods for Runners_Hi

end
